name: EasyConomy
version: @version@
main: dev.wwst.easyconomy.Easyconomy
api-version: "1.16"
softdepend: [Vault]
authors: [Weiiswurst, Geolykt]
description: Easy economy management
loadbefore: [Essentials]

commands:
  balance:
    description: "Shows the balance of a player"
    syntax: "/bal <player>"
    aliases:
      - bal
      - money
  eco:
    description: "Manage the economy"
    syntax: "/eco <give|take|set|backup> <player> <amount>"
    aliases:
      - economy
      - setbalance
      - setmoney
  pay:
    description: "Pay someone money"
    syntax: "/pay <target> <amount>"
    aliases:
      - paymoney
      - transferbalance
      - transferfunds
  baltop:
    description: "Shows the players with the highest balance"
    syntax: "/baltop"
    aliases:
      - balancetop
      - topbal
      - topbalance
  givemoney:
    description: "Gives the player a specific amount of money"
    syntax: "/givemoney <player> <amount>"
    aliases:
      - addmoney
  takemoney:
    description: "Gives a specific amount of money from a player"
    syntax: "/takemoney <player> <amount>"
    aliases:
      - removemoney
  setmoney:
    description: "Sets the amount of money of a given player"
    syntax: "/setmoney <player> <amount>"
    aliases:
      - setbalance
      - setbal
